### ISSUE TITLE
Missing dependency on lxml

### ISSUE THREAD

**Issue by velovix** [sync-or-swim/pyswim#4]
The results of generateDS are supposed to be compatible with the standard library's XML parser, but in my experience, that doesn't work.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/velovix/.virtualenvs/cooltest/lib/python3.8/site-packages/pyfixm/__init__.py", line 32121, in parse
    rootObj.build(rootNode, gds_collector_=gds_collector)
  File "/home/velovix/.virtualenvs/cooltest/lib/python3.8/site-packages/pyfixm/__init__.py", line 28761, in build
    self.ns_prefix_ = node.prefix
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'prefix'
```

However, if lxml is installed, the parsing works fine.

**Comment by BryceBeagle** [comment]
wait hold up... this seems very similar to the error we got when using the pyxb library?
